services:
  postgres:
    image: postgres:15
    container_name: home-inventory-postgres
    environment:
      POSTGRES_DB: home_inventory
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d home_inventory"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
